name: Check `clang-format` formatting

on:
  push:
    branches: [master, dev, ci-clang-formatting]
  pull_request:
    branches: [master, dev]

jobs:
  check_formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
    
      - name: Installing clang-format
        run: |
          sudo apt install clang-format
      - name: Check formatting for all .h and .c file.
        run: |
          for file in $(find . -name "*.h" -o -name "*.c"); do
            clang-format -style=file -output-replacements-xml $file | grep "<replacement " > /dev/null
            if [ $? -eq 0 ]; then
              echo "File $file is not formatted correctly, please run 'clang-format -i $file'" >&2
              IS_ALL_CORRECT=$false
            fi
          done
          if [ "$IS_ALL_CORRECT" = "$false" ]; then
            echo "Some files are not formatted correctly." >&2
            exit 1
          fi
